// Supabase Configuration
window.SUPABASE_URL = 'https://zjfzwqiudldkewnlelnn.supabase.co';
window.SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqZnp3cWl1ZGxka2V3bmxlbG5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg3NTI2MzksImV4cCI6MjA4NDMyODYzOX0.ZrulvRAHKXDp3E01BECprY8PVGnvQfECG_xZZ0DnhIE';
