-- LTI Dynamic Registration tokens
-- Short-lived tokens generated by the platform admin UI so that ADTA's
-- /lti-register page can confirm the registration was platform-initiated.
-- The token is passed in the URL to ADTA, then ADTA's backend forwards it
-- as Authorization: Bearer <token> when POSTing client metadata to our
-- /lti/register endpoint.

create table if not exists public.lti_registration_tokens (
  id          uuid primary key default gen_random_uuid(),
  token       text not null unique,
  org_id      uuid not null references public.orgs(id) on delete cascade,
  expires_at  timestamptz not null,
  consumed_at timestamptz
);

create index if not exists idx_lti_reg_tokens_token   on public.lti_registration_tokens(token);
create index if not exists idx_lti_reg_tokens_expires on public.lti_registration_tokens(expires_at);

alter table public.lti_registration_tokens enable row level security;

-- Only accessible via service role (platform worker)
create policy "lti registration tokens service role only"
on public.lti_registration_tokens
for all
using (false);
